# Generated by Django 5.1.7 on 2025-03-08 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_booking_no_of_guest_alter_menu_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="menu",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="restaurant.menu",
            ),
            preserve_default=False,
        ),
    ]
