# Generated by Django 5.1.7 on 2025-03-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_booking_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="name",
            new_name="tableno",
        ),
    ]
